---
services:
  mongodb:
    image: mongo
    container_name: mongodb
    ports:
      - "27018:27017"
    networks:
      - backend
    volumes:
      - mongodb_data:/data/db

  galleryapp:
    build: .
    container_name: galleryapp
    ports:
      - "3000:3000"
    depends_on:
      - mongodb
    networks:
      - backend

  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "443:443"
      - "80:80"
    depends_on:
      - galleryapp
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/certs:/etc/nginx/certs
      - ./nginx/openssl/openssl-1.0.2u:/opt/openssl-1.0.2u
    networks:
      - backend

networks:
  backend:
    driver: bridge

volumes:
  mongodb_data:
