services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27018:27017"
    volumes:
      - mongodb_data:/data/db
    networks:
      - backend
    environment:
      - MONGO_INITDB_DATABASE=galleryapp
    restart: unless-stopped

  galleryapp:
    build: .
    container_name: galleryapp
    ports:
      - "3000:3000"
    networks:
      - backend
    environment:
      - NODE_ENV=production
      - MONGODB_URI=mongodb://mongodb:27017/galleryapp
    restart: unless-stopped

  nginx:
    build:
      context: ./nginx
    container_name: nginx-ssl
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - galleryapp
    volumes:
      - ./nginx/certs:/etc/nginx/certs
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf 
    networks:
      - backend
    restart: unless-stopped

volumes:
  mongodb_data:

networks:
  backend:
    driver: bridge
