version: '3.8'

services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27018:27017"  # Exposed on host port 27018
    networks:
      - backend
    volumes:
      - mongodb_data:/data/db
    environment:
      - MONGO_INITDB_DATABASE=galleryapp  # Initialize DB (optional)
    restart: unless-stopped  # Auto-restart on failure
    healthcheck:
      test: ["CMD", "mongo", "--eval", "db.runCommand('ping')"]
      interval: 30s
      retries: 3
      start_period: 10s
      timeout: 10s

  galleryapp:
    build: .
    container_name: galleryapp
    ports:
      - "3000:3000"  # Exposed for direct access (dev/testing)
    networks:
      - backend
    environment:
      - NODE_ENV=production
      - MONGODB_URI=mongodb://mongodb:27017/galleryapp
    restart: unless-stopped

  nginx:
    image: nginx:latest
    container_name: nginx-proxy
    ports:
      - "80:80"     # HTTP
      - "443:443"   # HTTPS (instead of 4443 for standard HTTPS)
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/certs:/etc/nginx/certs:ro
      - ./nginx/html:/usr/share/nginx/html:ro  # Static files (optional)
    depends_on:
      - galleryapp
    networks:
      - backend
    restart: unless-stopped

  apache:
    build: .
    ports:
      - "443:443"
    depends_on:
      - galleryapp

  galleryapp:
    image: your-gallery-app-image
    ports:
      - "3000:3000"

networks:
  backend:
    driver: bridge

volumes:
  mongodb_data:
