version: '3.8'

services:
  mongodb:
    image: mongo
    container_name: mongodb
    ports:
      - "27018:27017"
    networks:
      - backend
    volumes:
      - mongodb_data:/data/db

  galleryapp:
    build: .
    container_name: galleryapp
    ports:
      - "3000:3000"
    depends_on:
      - mongodb
    networks:
      - backend

  apache:
    image: apache-ssl-proxy:latest
    container_name: apache-proxy
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./apache/httpd.conf:/usr/local/apache2/conf/httpd.conf:ro
      - ./apache/000-default.conf:/usr/local/apache2/conf/extra/httpd-vhosts.conf:ro
      - ./apache/default-ssl.conf:/usr/local/apache2/conf/extra/httpd-ssl.conf:ro
      - ./apache/certs:/usr/local/apache2/conf/ssl:ro
    restart: unless-stopped
    depends_on:
      - galleryapp
    networks:
      - backend

networks:
  backend:
    driver: bridge

volumes:
  mongodb_data:

