---

services:
  mongodb:
    image: mongo
    container_name: mongodb
    ports:
      - "27018:27017"
    networks:
      - backend
    volumes:
      - mongodb_data:/data/db

  galleryapp:
    build: .
    container_name: galleryapp
    ports:
      - "3000:3000"
    depends_on:
      - mongodb
    networks:
      - galleryapp_backend

  nginx:
    image: nginx:alpine
    container_name: nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/conf.d:/etc/nginx/conf.d:ro
      - ./nginx/certs:/etc/nginx/certs:ro
    depends_on:
      - galleryapp
    networks:
      - backend

networks:
  backend:
    driver: bridge

volumes:
  mongodb_data:

