version: '3.8'

services:
  apache:
    image: apache-ssl-proxy:latest
    container_name: apache-proxy
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./apache/httpd.conf:/usr/local/apache2/conf/httpd.conf:ro
      - ./apache/000-default.conf:/usr/local/apache2/conf/extra/httpd-vhosts.conf:ro
      - ./apache/default-ssl.conf:/usr/local/apache2/conf/extra/httpd-ssl.conf:ro
      - ./apache/certs:/etc/apache2/ssl:ro
    restart: unless-stopped
